name: save_the_potato
description: "Save The Potato â€“ Get ready for some non-stop, spin-tastic fun! Your goal? Keep our potato pal from turning into a hot tot or an ice cube."
publish_to: 'none'
version: 1.4.1+10401

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flame: ^1.18.0
  flame_noise: ^0.1.1+12
  flutter_bloc: ^8.1.6
  flame_bloc: ^1.12.0
  equatable: ^2.0.5
  flame_rive: ^1.10.2
  rive: ^0.12.3
  shared_preferences: ^2.3.2
  get_it: ^7.6.7
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0
  cloud_functions: ^5.0.4
  toastification: ^2.2.0
  url_launcher: ^6.2.3
  device_info_plus: ^10.1.2
  uuid: ^4.3.3
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.9
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  stream_transform: ^2.1.0
  wiredash: ^2.1.2
  flutter_soloud: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Cookies
      fonts:
        - asset: assets/fonts/Cookies.ttf

  assets:
    - assets/images/flame/
    - assets/images/flutter_flame/
    - assets/images/snow/
    - assets/images/sparkle/
    - assets/images/orb/
    - assets/images/heart/
    - assets/images/trophy/
    - assets/images/icons/
    - assets/images/
    - assets/fonts/
    - assets/audio/
    - assets/audio/motivation/
    - assets/rive/
    - assets/logo/

  shaders:
    - shaders/background.frag

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo-1024.png"
  min_sdk_android: 21